### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by limavfabio** [Efiamotu-1/To-do-list#6]
Your project is looking great! The drag and drop implementation is working as expected except for the local storage, I believe you forgot to make the changes persistent to the local storage to keep them throughout page reloads. Overall your project is really good, keep up the hard work!

**Comment by cmolinan** [comment]
Your implementation of drag&drop is excellent.
Maybe you could add another option to activate the menu by double clicking on one of the items.
Congratulations Habib!

**Comment by DhuruvSingh** [comment]
# The drag & drop working excellent 
I can see this in your to-do list. when we edit any list item it remains open the input. I would like to suggest please implement the changes to this issue.

> Congrats 💯

**Comment by Efiamotu-1** [comment]
Thanks for the review, the changes have all been effected
